{% set version = '1.6.3' %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lava
  version: {{ version|replace("-", "_") }}

source:
  fn: lava_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/lava_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lava/lava_{{ version }}.tar.gz
  sha256: 8e75ab929543157e0f72baa33562ceea8b25ca2efb1cba17a3220f9faf965e31

build:
  merge_build_host: True  # [win]
  number: 1
  skip: true  # [win32]
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]
  host:
    - r-base
    - r-squarem
    - r-numderiv
    - r-survival
  run:
    - r-base
    - r-squarem
    - r-numderiv
    - r-survival

test:
  commands:
    - $R -e "library('lava')"           # [not win]
    - "\"%R%\" -e \"library('lava')\""  # [win]

about:
  home: https://github.com/kkholst/lava
  license: GPL-3
  summary: "A general implementation of Structural Equation Models with latent variables (MLE,
    2SLS, and composite likelihood estimators) with both continuous, censored, and ordinal
    outcomes (Holst and Budtz-Joergensen (2013) <doi:10.1007/s00180-012-0344-y>). Mixture
    latent variable models and non-linear latent variable models (two-stage)...\t\t
    The package also provides methods for graph exploration (d-separation, back-door
    criterion), simulation of general non-linear latent variable models, and estimation
    of influence functions for a broad range of statistical models. "
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'  # [unix]
  license_file: '{{ environ["PREFIX"] }}\R\share\licenses\GPL-3'  # [win]

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
    - cbrueffer
