{% set version = "1.7.3" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-lava
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/lava_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/lava/lava_{{ version }}.tar.gz
  sha256: 4e087df1350b05c3d0403597a1ad97f4b0e183047d5d8636a62143f26bd86a08

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-squarem
    - r-future.apply
    - r-numderiv
    - r-progressr
    - r-survival
  run:
    - r-base
    - r-squarem
    - r-future.apply
    - r-numderiv
    - r-progressr
    - r-survival

test:
  commands:
    - $R -e "library('lava')"           # [not win]
    - "\"%R%\" -e \"library('lava')\""  # [win]

about:
  home: https://github.com/kkholst/lava
  license: GPL-3.0-only
  summary: 'A general implementation of Structural Equation Models with latent variables (MLE, 2SLS, and composite likelihood estimators) with both continuous, censored, and ordinal outcomes (Holst and Budtz-Joergensen (2013) <doi:10.1007/s00180-012-0344-y>). Mixture latent variable models and non-linear latent variable
    models (Holst and Budtz-Joergensen (2019) <doi:10.1093/biostatistics/kxy082>). The package also provides methods for graph exploration (d-separation, back-door criterion), simulation of general non-linear latent variable models, and estimation of influence functions for a broad range of statistical models. '
  license_family: GPL3
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: lava
# Type: Package
# Title: Latent Variable Models
# Version: 1.6.6
# Date: 2019-08-01
# Authors@R: c(person("Klaus K.", "Holst", email="klaus@holst.it", role=c("aut", "cre")), person("Brice", "Ozenne", role = "ctb"), person("Thomas", "Gerds", role = "ctb"))
# Author: Klaus K. Holst [aut, cre], Brice Ozenne [ctb], Thomas Gerds [ctb]
# Maintainer: Klaus K. Holst <klaus@holst.it>
# Description: A general implementation of Structural Equation Models with latent variables (MLE, 2SLS, and composite likelihood estimators) with both continuous, censored, and ordinal outcomes (Holst and Budtz-Joergensen (2013) <doi:10.1007/s00180-012-0344-y>). Mixture latent variable models and non-linear latent variable models (Holst and Budtz-Joergensen (2019) <doi:10.1093/biostatistics/kxy082>). The package also provides methods for graph exploration (d-separation, back-door criterion), simulation of general non-linear latent variable models, and estimation of influence functions for a broad range of statistical models.
# URL: https://github.com/kkholst/lava
# BugReports: https://github.com/kkholst/lava/issues
# License: GPL-3
# LazyLoad: yes
# Depends: R (>= 3.0)
# Imports: grDevices, graphics, methods, numDeriv, stats, survival, SQUAREM, utils
# Suggests: KernSmooth, Matrix, Rgraphviz, data.table, ellipse, fields, foreach, geepack, gof (>= 0.9), graph, igraph (>= 0.6), lava.tobit (>= 0.4.7), lme4, mets (>= 1.1), nlme, optimx, polycor, quantreg, rgl, testthat (>= 0.11), visNetwork, zoo
# ByteCompile: yes
# Encoding: UTF-8
# RoxygenNote: 6.1.1
# NeedsCompilation: no
# Packaged: 2019-08-01 21:34:45 UTC; klaus
# Repository: CRAN
# Date/Publication: 2019-08-01 22:20:02 UTC
