# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "fgftsZ5VRlVkeilgrqCvpjEnPUUWAy8YUI6wyQeACPJqocsUktmSNB9QXhd4YIr5GChIcBM8TEr9kTjL6F/zLdZY4L1koPRWiCYEQsFlPRh05cTkk0YdrRh9d344g63Z/IXcYyoVr+E+sGvKHPlKBf4YVdixCgNNwhqd+OwZcDknevMt5YunAzUv3e7DdZY9XRy+aZIgmeu5frtq85h9nFd9LaLrJ9VcJE6hqnC6LlBEN0mMhJEyu66lr403gPW3akYAieDpKtJEfSAkF0INUQYb2zsgUslZMdbwRuKgVfKuk1HTsvMvGtVurZZvEYAW8e74DP65TKijwIzEpG9PfG3XIJ+eVJzEcWVFP2I4ifxQHM2ZB/re+u9r8e1cPCYuvvAkyasSSa8LxGIjTuy8y2ZJvbwpT1+U/Y4GZB+K7N5oXERCIodz3VsnZo2m8a4dsmfipsK4SlMPJt9rhKHyTriiodMpjpFRtuwCU+ygpmC7yyxefbFEk+4YZN6Mf9GxF0NNiXnONhF7wp2l09MJ5+g+TgBb/XVm88qJnC999pjxRa7dRaQJMIe9wN7CYsECij60JY+xe92CQ/oJk49uom5hcxu8hMt0quRQJhh0bhr+8QmHy6oz502Hg5Ip2caMaLYllktvaB9VC5PtPDMcZpSGQ8itZ8XFHBWuXF1enwY="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
