travis:
  secure:
    BINSTAR_TOKEN: Y9h+3K9YXg0IXxvhldG2k4hlcF6Uysjrau1qCKgANrPWwhF4dEUi+aIDSU1NS9ad3IPH8lJyahAGGtfuJFNuiICnFyPX2zIKGsL6Njkz8ouYirO9pE4zOgfJ8nXb+gxkMArujG/QkB+ZGaYUfu9Z7GGftC+2tSATOrOGyLUQ9Q/twjya/VWdDoQhXjEPDGILXRmJMXzpp9jksJXnVBEYAXgmYoO2K7MHP8xySZmAx7a0wuVuj6PhWpfBYVJXXnSs0DQkWW8L/QZWw9DRkNRG0AS06kTOIV/MRHBbYu5kjOQVDzAVhN74x4Bn7tNZ/bLCHKW6rJg7wnKxdYZBwzLr20jkDwtYrsYmJnuOIf/rFpMY+quQ6a/M+8SI9wmRcemI4x49HPA9c0CNgsH/w/2Zg3fDeyXy72AiLGiNhed6+Mpyr6lbEi+n49TelV5c64CPoNT7eFCKRdNE86VzZg/9CSjDjKLweU3f3iZShMCo938xwcjhea8b5SR+GzSSVADN2KgzelQkAErL5erA5+HYojCZ/HrXeiBtLExkV3r5PNlv8l5LYzjHdIRV0EdgS+kZpnKszJN9+mbuqcYysw+r2ZhrPEqWxIdVX1yN7VZNNcXQ0fMoK+VfAQFlbCFn/fmWL+SX1DsUg2i+JHSn/q2NgvYnI1y4RjuODgO6BkH1noI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
