travis:
  secure:
    BINSTAR_TOKEN: U+SnSmaRzbL11RF/EN+LQCDEZ6NtsXyAjBBNnbxsIb9q4FnQMwof/MzT7a/7ilLqLPje8V1M44WZ/XEoUaBEUOieysasD+jDKF84Fvo3r9FkDZX7G43GL99UHbe7Vmh+wio2lQK25vux5PV6YARDB0+yyz0kjpZs1YfqSUmAsgZNYEVJoAnmvuMx0JraqxQaH5nolIzoduf3ALk2vXyprzn7yVPsSMxiP9m14oF8wg+0zy7i+6gprWH+WVCbYn51AC5HQXLztaLydyKNMPhL/p3DmSoOG5LfI/K5nGYk2Weiz4DEbv4Ao/bTOcWUITEIuVG+472CzvXFzLp/41FujWeBG2HoiVaQrt50bjIjoWwXeAVL+6qeXpmvKEs0CIj363Otqa2dCwuz5KQpQEFav/w7D+NT28qhIHnLKOFn3cUx5ZsWuoh4wmMkb8W1j+gA9yFlIb0HW0kXMIFol08ivOvU8r4yNRvkl2uPdHROdA33Vs3AakqzOLJh3PJCz7OboplofdkYOStOnCxpwsT3UrpHxkLd1pmrFa52ghEJQxYbKwYJUu59W2pcOlUuQXBYzkuINpqJIXz5XwY7LCThQfwEgi/T0FmCAwYYkLaC/s1snR5wN/tpubY52opxYkN+VlhvcweYFh0Pq9168B9OTnphO9CW028SVCzTn/uMGGI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
